-- Deep-dive series seed. Mirrors app/src/data/series.ts.

insert into public.series (id, title, description, category, language) values
  ('series-money-basics', 'Money Basics',
   'From your first emergency fund to picking the right mutual fund plan — in order.',
   'finance', 'en'),
  ('series-focus-fundamentals', 'Focus Fundamentals',
   'Beat procrastination, build deep-work blocks, and make habits stick.',
   'productivity', 'en'),
  ('series-speak-with-impact', 'Speak with Impact',
   'Interviews, negotiations, emails, and presentations that land.',
   'communication', 'en'),
  ('series-tech-literacy', 'Tech Literacy 101',
   'APIs, the cloud, caching, and AI — the concepts behind every app you use.',
   'technology', 'en'),
  ('series-protect-your-money', 'Protect Your Money',
   'Insurance, credit scores, hidden fees, and the traps that quietly drain wealth.',
   'finance', 'en'),
  ('series-digital-self-defence', 'Digital Self-Defence',
   'Phishing, passwords, permissions, and staying private in a tracked world.',
   'technology', 'en'),
  ('series-be-heard-at-work', 'Be Heard at Work',
   'Pitch yourself, speak up, give feedback, and ask for the raise.',
   'communication', 'en'),
  ('series-work-smarter', 'Work Smarter',
   'Prioritize ruthlessly, batch the noise, and protect your energy and sleep.',
   'productivity', 'en')
on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  language = excluded.language;

insert into public.series_lessons (series_id, lesson_id, position) values
  ('series-money-basics', 'fin-003', 0),
  ('series-money-basics', 'fin-006', 1),
  ('series-money-basics', 'fin-004', 2),
  ('series-money-basics', 'fin-002', 3),
  ('series-money-basics', 'fin-005', 4),
  ('series-money-basics', 'fin-001', 5),
  ('series-focus-fundamentals', 'prod-001', 0),
  ('series-focus-fundamentals', 'prod-005', 1),
  ('series-focus-fundamentals', 'prod-002', 2),
  ('series-focus-fundamentals', 'prod-003', 3),
  ('series-focus-fundamentals', 'prod-004', 4),
  ('series-focus-fundamentals', 'prod-006', 5),
  ('series-speak-with-impact', 'comm-001', 0),
  ('series-speak-with-impact', 'comm-004', 1),
  ('series-speak-with-impact', 'comm-003', 2),
  ('series-speak-with-impact', 'comm-005', 3),
  ('series-speak-with-impact', 'comm-002', 4),
  ('series-speak-with-impact', 'comm-006', 5),
  ('series-tech-literacy', 'tech-001', 0),
  ('series-tech-literacy', 'tech-006', 1),
  ('series-tech-literacy', 'tech-002', 2),
  ('series-tech-literacy', 'tech-004', 3),
  ('series-tech-literacy', 'tech-003', 4),
  ('series-tech-literacy', 'tech-005', 5),
  ('series-protect-your-money', 'fin-008', 0),
  ('series-protect-your-money', 'fin-009', 1),
  ('series-protect-your-money', 'fin-012', 2),
  ('series-protect-your-money', 'fin-015', 3),
  ('series-protect-your-money', 'fin-013', 4),
  ('series-protect-your-money', 'fin-011', 5),
  ('series-digital-self-defence', 'tech-015', 0),
  ('series-digital-self-defence', 'tech-007', 1),
  ('series-digital-self-defence', 'tech-011', 2),
  ('series-digital-self-defence', 'tech-008', 3),
  ('series-digital-self-defence', 'tech-013', 4),
  ('series-digital-self-defence', 'tech-014', 5),
  ('series-be-heard-at-work', 'comm-007', 0),
  ('series-be-heard-at-work', 'comm-010', 1),
  ('series-be-heard-at-work', 'comm-008', 2),
  ('series-be-heard-at-work', 'comm-014', 3),
  ('series-be-heard-at-work', 'comm-011', 4),
  ('series-be-heard-at-work', 'comm-013', 5),
  ('series-work-smarter', 'prod-008', 0),
  ('series-work-smarter', 'prod-007', 1),
  ('series-work-smarter', 'prod-013', 2),
  ('series-work-smarter', 'prod-014', 3),
  ('series-work-smarter', 'prod-009', 4),
  ('series-work-smarter', 'prod-015', 5)
on conflict (series_id, lesson_id) do update set position = excluded.position;
