// Generates supabase/seed/seed_lessons.sql from the app's bundled lesson data
// so demo mode and the hosted backend share one source of truth.
// Usage: node --experimental-strip-types scripts/generate-seed.mjs
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const { SEED_LESSONS } = await import(join(root, 'app/src/data/lessons.ts'));

const q = (value) => (value == null ? 'null' : `'${String(value).replace(/'/g, "''")}'`);
const arr = (values) => `array[${values.map(q).join(', ')}]`;

const rows = SEED_LESSONS.map(
  (l) =>
    `  (${q(l.id)}, ${q(l.title)}, ${q(l.category)}, ${l.durationSeconds}, ${q(l.videoUrl)}, ${q(
      l.thumbnailUrl
    )}, ${q(l.quizQuestion)}, ${arr(l.quizOptions)}, ${l.quizCorrectIndex}, ${q(l.structureHook)}, ${q(
      l.structureConcept
    )}, ${q(l.structureExample)}, ${q(l.structureTakeaway)}, ${q(l.tryThisToday ?? null)}, ${
      l.qualityScore
    }, ${q(l.language)})`
).join(',\n');

const sql = `-- Generated by scripts/generate-seed.mjs — do not edit by hand.
-- Source of truth: app/src/data/lessons.ts

insert into public.lessons (
  id, title, category, duration_seconds, video_url, thumbnail_url,
  quiz_question, quiz_options, quiz_correct_index,
  structure_hook, structure_concept, structure_example, structure_takeaway,
  try_this_today, quality_score, language
) values
${rows}
on conflict (id) do update set
  title = excluded.title,
  category = excluded.category,
  duration_seconds = excluded.duration_seconds,
  video_url = excluded.video_url,
  thumbnail_url = excluded.thumbnail_url,
  quiz_question = excluded.quiz_question,
  quiz_options = excluded.quiz_options,
  quiz_correct_index = excluded.quiz_correct_index,
  structure_hook = excluded.structure_hook,
  structure_concept = excluded.structure_concept,
  structure_example = excluded.structure_example,
  structure_takeaway = excluded.structure_takeaway,
  try_this_today = excluded.try_this_today,
  quality_score = excluded.quality_score,
  language = excluded.language;
`;

const outPath = join(root, 'supabase/seed/seed_lessons.sql');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, sql);
console.log(`Wrote ${SEED_LESSONS.length} lessons to ${outPath}`);
